<template>
	<div class="h-full flex flex-row py-10 px-16" data-tauri-drag-region>
		<div class="pr-16 flex flex-col h-full select-none" data-tauri-drag-region>
			<div class="select-none cursor-default font-permanent-marker text-4xl" data-tauri-drag-region>settings</div>
		</div>
		<div class="h-full flex-grow overflow-scroll">
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
			settings<br>
		</div>
	</div>
</template>
