[package]
name = "wiwipaccer"
version = "0.0.0"
# description = ""
authors = ["Meadowsys"]
license = "AGPL-3.0-only"
repository = "https://github.com/Meadowsys/wiwipaccer"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.2", features = ["shell-open", "system-tray"] }
tokio = { version = "1.25.0", features = ["full"] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
