[package]
name = "wiwipaccer-util"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
nominal = { path = "../nominal", features = ["serde"] }
ron.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
