[workspace]
resolver = "2"
members = [
	"packages/app-desktop",
	"packages/app-frontend",
	"packages/decl",
	"packages/model",
	"packages/provider-plugin-api",
	"packages/provider-plugin-host",
	"packages/provider-plugin-random-cube-all",
	"packages/standard-models"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Meadow Liu <meadowsys@kiwin.gay>"]
repository = "https://github.com/meadowsys/wiwipaccer"
license = "AGPL-3.0-only"
publish = false

[workspace.dependencies.hashbrown]
version = "0.15.2"

[workspace.dependencies.semver]
version = "1.0.23"

[workspace.dependencies.wasmtime]
version = "26.0.0"
default-features = false
features = [
	# todo reassess these features?
	"runtime",
	"cranelift",
	"component-model"

	# "async",
	# "demangle",
	# "coredump",
	# "addr2line",

	# I dunno if beneficial
	# "pooling-allocator"

	# for debugging guest code
	# "profiling"

	# for debugging guest code
	# "debug-builtins"
]

[workspace.dependencies.wit-bindgen]
version = "0.41.0"

[workspace.dependencies.wiwi]
git = "https://github.com/meadowsys/wiwi"
rev = "f000a24fa11c6e6d2fbf078f20bd8e571efd2d15"

[workspace.dependencies.wiwipaccer-decl]
path = "packages/decl"

[workspace.dependencies.wiwipaccer-provider-plugin-api]
path = "packages/provider-plugin-api"

[workspace.dependencies.wiwipaccer-model]
path = "packages/model"
