[workspace]
resolver = "2"
members = [
	"app/src-tauri",
	"lib/core",
	"lib/nom"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies]
async-trait = "0.1.75"
camino = "1.1.6"
futures = "0.3.29"
hashbrown = { version = "0.14.3", features = ["serde"] }
ron = "0.8.1"
semver = "1.0.20"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
thiserror = "1.0.51"
tokio = { version = "1.35.1", features = ["full"] }

[profile.dev]
opt-level = 0 # none
debug-assertions = true
debug = true
incremental = true

[profile.release]
opt-level = 3 # all
debug-assertions = false
lto = true
codegen-units = 1
