[workspace]
resolver = "2"
members = [
	"app/src-tauri",
	"lib"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "AGPL-3.0-only"

[workspace.dependencies]
hashbrown = { version = "0.14.3", features = ["serde"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["full"] }

[profile.dev]
opt-level = 0 # none
debug-assertions = true
debug = true
incremental = true

[profile.release]
opt-level = 3 # all
debug-assertions = false
lto = true
codegen-units = 1
