[workspace]
resolver = "2"
members = [
	"packages/app-desktop",
	"packages/app-frontend",
	"packages/decl",
	"packages/model",
	"packages/provider-plugin-api",
	"packages/provider-plugin-host",
	"packages/provider-plugin-random-cube-all",
	"packages/standard-models"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Meadow Liu <meadowsys@kiwin.gay>"]
repository = "https://github.com/meadowsys/wiwipaccer"
license = "AGPL-3.0-only"
publish = false

[workspace.dependencies.console-error-panic-hook]
package = "console_error_panic_hook"
version = "0.1.7"

[workspace.dependencies.hashbrown]
version = "0.15.2"

[workspace.dependencies.leptos]
version = "0.7.7"
features = ["csr"]

[workspace.dependencies.mimalloc]
version = "0.1.44"

[workspace.dependencies.semver]
version = "1.0.26"

[workspace.dependencies.surrealdb]
version = "2.2.1"
default-features = false
features = ["kv-rocksdb"]

[workspace.dependencies.tauri]
version = "2.3.1"

[workspace.dependencies.tauri-build]
version = "2.0.6"

[workspace.dependencies.wasm-bindgen]
version = "0.2.100"

[workspace.dependencies.wasmtime]
version = "30.0.2"
default-features = false
features = [
	# todo reassess these features?
	"runtime",
	"cranelift",
	"component-model"

	# "async",
	# "demangle",
	# "coredump",
	# "addr2line",

	# I dunno if beneficial
	# "pooling-allocator"

	# for debugging guest code
	# "profiling"

	# for debugging guest code
	# "debug-builtins"
]

[workspace.dependencies.wit-bindgen]
version = "0.41.0"

[workspace.dependencies.wiwi]
git = "https://github.com/meadowsys/wiwi"
rev = "935c90e3ac68dc9f9a09690b8dd9e35f9db0d0cf"

[workspace.dependencies.wiwipaccer-decl]
path = "packages/decl"

[workspace.dependencies.wiwipaccer-provider-plugin-api]
path = "packages/provider-plugin-api"

[workspace.dependencies.wiwipaccer-model]
path = "packages/model"

[patch.crates-io]
tauri = { git = "https://github.com/tauri-apps/tauri", rev = "f2c94aaca074bf15164d08e959b67f67f4c934ed" }
tauri-build = { git = "https://github.com/tauri-apps/tauri", rev = "f2c94aaca074bf15164d08e959b67f67f4c934ed" }
