[workspace]
members = [
	"lib",
	"src-tauri"
]

[profile.dev]
opt-level = 0 # none
debug-assertions = true
debug = true
lto = false
incremental = true
codegen-units = 1024
panic = "unwind"
overflow-checks = true
