[toolchain]
channel = "nightly-2025-01-03"
profile = "minimal"
components = [
	"clippy",
	"llvm-tools",
	"rust-analyzer",
	"rust-docs",
	"rust-src"
]
targets = [
	"wasm32-unknown-unknown",
	"wasm32-wasip2"
]
