[package]
name = "wiwipaccer-pack"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
hashbrown.workspace = true
nominal = { path = "../nominal", features = ["serde"] }
semver.workspace = true
serde.workspace = true
thiserror.workspace = true
