[package]
name = "nominal"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
serde = { workspace = true, optional = true }

[features]
serde = ["dep:serde"]
