[package]
name = "wiwipaccer-common"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
boxed = { path = "../boxed" }
ts-result = { path = "../ts-result" }
