[package]
name = "wiwipaccer"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "=2.0.0-alpha.13", features = [] }

[dependencies]
camino.workspace = true
hex = "0.4.3"
mimalloc = "0.1.39"
rfd = "0.12.1"
serde_json.workspace = true
surrealdb = { version = "1.1.0", features = ["kv-speedb"], default-features = false }
tauri = { version = "=2.0.0-alpha.20", features = ["macos-private-api"] }
thiserror.workspace = true
tokio.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
