[package]
name = "wiwipaccer-app"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[build-dependencies]
tauri-build = { version = "=2.0.0-alpha.13", features = [] }

[dependencies]
tauri = { version = "=2.0.0-alpha.20", features = [] }
serde_json.workspace = true

[features]
custom-protocol = ["tauri/custom-protocol"]
