[package]
name = "mc-versions-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
chrono = { version = "0.4.31", default-features = false }
proc-macro2 = "1.0.76"
quote = "1.0.35"
serde.workspace = true
serde_json.workspace = true

[lib]
proc-macro = true
