[package]
name = "surrealdb-dep"
version.workspace = true
edition.workspace = true

[dependencies.surrealdb]
git = "https://github.com/surrealdb/surrealdb.git"
rev = "54aedcdbdc1c50a55dfaec8f206c4c715ad3cb40" # 1.0.0
default-features = false
features = ["kv-speedb"]
