name: build (Windows)
on:
- push

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: setup rust
      shell: bash
      run: |
        rustup target add x86_64-pc-windows-gnu
        rustc --version

    - name: setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    - name: setup node
      shell: bash
      run: pnpm node -v

    - name: print store path
      shell: bash
      id: store-path
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: cache pnpm store
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
      with:
        path: ${{ steps.store-path.outputs.STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: pnpm-store-${{ runner.os }}

    - name: install node deps
      shell: bash
      run: pnpm i

    - name: install sccache
      shell: bash
      run: |
        mkdir sccache
        cd sccache
        curl -L -o sccache.tar.gz https://github.com/mozilla/sccache/releases/download/v0.3.3/sccache-v0.3.3-x86_64-pc-windows-msvc.tar.gz
        tar --strip-components 1 -xvf sccache.tar.gz
        cd ..

        echo "RUSTC_WRAPPER=$(pwd)/sccache/sccache" >> $GITHUB_ENV
        echo "SCCACHE_DIR=$(pwd)/sccache" >> $GITHUB_ENV

    - name: build app
      shell: bash
      run: pnpm tauri build --target x86_64-pc-windows-gnu -- -Z build-std # TODO THIS

    - name: upload app artifact
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: windows-msi
        path: target/x86_64-pc-windows-gnu/release/bundle/dmg/*.dmg # TODO THIS
