name: build (Linux)
on:
- push

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ubuntu:16.04

    steps:
    - name: install system dependencies
      run: |
        apt-get update
        apt-get install software-properties-common
        add-apt-repository -y ppa:git-core/ppa
        apt-get install -y \
           build-essential \
           curl \
           git \
           libayatana-appindicator3-dev \
           libclang-dev \
           libgtk-3-dev \
           librsvg2-dev \
           libssl-dev \
           libwebkit2gtk-4.0-dev \
           wget

    - name: checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: setup rustup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh /dev/stdin --profile minimal -y --no-modify-path
        echo "$HOME/.cargo/bin" >> $GITHUB_ENV

    - name: setup rust
      run: rustc --version

    - name: setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    - name: setup node
      run: pnpm node -v

    - name: print store path
      id: store-path
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: cache pnpm store
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
      with:
        path: ${{ steps.store-path.outputs.STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: pnpm-store-${{ runner.os }}

    - name: install node deps
      run: pnpm i

    - name: install sccache
      run: |
        brew install sccache
        echo "RUSTC_WRAPPER=$(which sccache)" >> $GITHUB_ENV
        echo "SCCACHE_DIR=$(pwd)/sccache" >> $GITHUB_ENV
        echo /sccache >> .git/info/exclude

    - name: build app
      run: pnpm tauri build --target x86_64-unknown-linux-gnu -- -Z build-std

    - name: upload app artifact (deb)
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: linux-deb
        path: target/x86_64-unknown-linux-gnu/release/bundle/deb/*.deb

    - name: upload app artifact (appimage)
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: linux-appimage
        path: target/x86_64-unknown-linux-gnu/release/bundle/appimage/*.AppImage
