name: ci
on:
  push:
    branches:
    - "**"

concurrency:
  group: ci-${{ github.ref }}-${{ github.ref == 'refs/heads/wiwi' && contains(github.event.head_commit.message, '[release rolling]') }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    strategy:
      fail-fast: false
      matrix:
        target:
        - target-triple: aarch64-apple-darwin
          runs-on: macos-14
        - target-triple: x86_64-apple-darwin
          runs-on: macos-14

        - target-triple: x86_64-unknown-linux-musl
          runs-on: ubuntu-22.04
          apt:
          - build-essential
          - curl
          - file
          - git
          - javascriptcoregtk-4.1-dev
          - libayatana-appindicator3-dev
          - libclang-dev
          - libglib2.0-dev
          - libgtk-3-dev
          - librsvg2-dev
          - libsoup-3.0-dev
          - libssl-dev
          - libwebkit2gtk-4.1-dev
          - wget

        - target-triple: x86_64-pc-windows-msvc
          runs-on: windows-2022

    runs-on: ${{ matrix.target.runs-on }}
    container: ${{ matrix.target.container-image }}
    steps:
    - name: install system dependencies
      if: matrix.target.apt
      run: |
        sudo add-apt-repository -y ppa:git-core/git
        sudo apt-get install -y ${{ join(matrix.target.apt, ' ') }}
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: setup rust
      run: |
        rustup target add ${{ matrix.target.target-triple }}
        rustc --version

    - name: setup bun
      uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1.1.1

    - name: install frontend deps
      run: bun i

    - name: build app
      run: bun tauri build --target ${{ matrix.target.target-triple }} -- -Z build-std

    - name: upload app artifact
      uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
      with:
        name: wiwipaccer-${{ matrix.target.target-triple }}
        # lazy, should be improved
        path: target/${{ matrix.target.target-triple }}/release/bundle/*
