name: deploy site
on:
  push:
    branches:
    # - "wiwi"
    - "disabled"
    paths:
    - "site/**"

concurrency:
  group: deploy-site
  cancel-in-progress: true

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    # - name: setup pnpm
    #   uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    # - name: setup node
    #   run: pnpm node -v

    # - name: print store path
    #   id: store-path
    #   run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    # - name: cache pnpm store
    #   uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
    #   with:
    #     path: ${{ steps.store-path.outputs.STORE_PATH }}
    #     key: pnpm-store-sitebuild-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
    #     restore-keys: pnpm-store-sitebuild-${{ runner.os }}

    # - name: install node deps
    #   run: pnpm i

    # - name: build site
    #   working-directory: site
    #   run: pnpm run generate

    # - name: checkout gh-pages branch
    #   uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
    #   with:
    #     path: gh-pages
    #     ref: gh-pages

    # - name: install fish shell
    #   run: |
    #     sudo add-apt-repository -yn ppa:fish-shell/release-3
    #     sudo apt-get update
    #     sudo apt-get install fish

    # - name: deploy
    #   shell: fish {0}
    #   run: |
    #     rm -rf gh-pages/*
    #     mv gh-pages/.git gh-pages/git
    #     rm -rf gh-pages/.*
    #     mv gh-pages/git gh-pages/.git

    #     cp -R site/.output/public/* gh-pages
    #     cp -R site/.output/public/.* gh-pages
    #     cp .gitignore gh-pages/.gitignore

    #     set COMMIT_MESSAGE "(automated) deploy from commit "(git rev-parse HEAD)

    #     cd gh-pages

    #     git config --global user.name "${{ secrets.GENVERSIONS_AUTOCOMMITTER_NAME }}"
    #     git config --global user.email "${{ secrets.GENVERSIONS_AUTOCOMMITTER_EMAIL }}"
    #     echo https://meadowsys:${{ secrets.GHPAT }}@github.com > .git/credentials
    #     git config --global credential.helper "store --file=.git/credentials"
    #     git config --unset-all http.https://github.com/.extraheader # https://stackoverflow.com/a/69979203

    #     git add -A
    #     git commit -m "$COMMIT_MESSAGE"
    #     git push
