name: check for MC releases
on:
  schedule:
  - cron: 0 * * * *
  workflow_dispatch:
  push:
    paths:
    - "packages/mc-versions-macro/**"
    - "!packages/mc-versions-macro/src/version_manifest_v2.json"

concurrency:
  group: mc-releases
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-22.04

    steps:
    - name: checkout code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: fetch new versions data
      id: new
      run: |
        curl -sSf https://piston-meta.mojang.com/mc/game/version_manifest_v2.json > packages/mc-versions-macro/src/version_manifest_v2.json
        if [ -z "$(git status --porcelain=v1 2>/dev/null)" ]; then
          echo "new=false" >> $GITHUB_OUTPUT
        else
          echo "new=true" >> $GITHUB_OUTPUT
        fi

    - name: commit/push
      if: steps.new.outputs.new == 'true'
      run: |
        git config --global user.name ${{ secrets.GENVERSIONS_AUTOCOMMITTER_NAME }}
        git config --global user.email ${{ secrets.GENVERSIONS_AUTOCOMMITTER_EMAIL }}

        echo "https://meadowsys:${{ secrets.GHPAT }}@github.com" > .git/credentials
        git config --global credential.helper "store --file=.git/credentials"

        # https://stackoverflow.com/a/69979203
        git config --unset-all http.https://github.com/.extraheader

        git add -A
        git commit -m "(automated) updating mc releases"
        git push
